### ISSUE TITLE
How to obtain selected data?

### ISSUE THREAD

**Issue by tjhighpoint** [arendjr/select3#2]
I have a select tag named "element". I use select3 like this:   
     $('#element').select3({multiple:true}).

It works fine, but when I select items I want the data accessible in code. When I use this
     $('#element').select3('data') 
as the API indicates, I get this error:

    Cannot call method on element without Select3 instance

Can you tell me what I'm doing wrong?

**Comment by arendjr** [comment]
Hi there,

This appears to be a bug with the newly introduced "traditional" module (that allows you to transform a &lt;select&gt; box in the DOM into a Select3 instance). I've fixed the bug and added a test case.

Your method of accessing the data looks fine, so once you update to the version I just pushed it should work.

Thanks for the report!

Cheers,
Arend jr.

**Comment by tjhighpoint** [comment]
Thanks. Also when I precreate the select box with some options 'selected', I was expecting they'd also be auto-added as selected-items during the transform, but they don't seem to be. I can verify the options are in the selected state.

**Comment by tjhighpoint** [comment]
Spoke too soon - the new version fixes that too!  Thank you.
