### ISSUE TITLE
Load items dynamically from custom source

### ISSUE THREAD

**Issue by hekike** [arendjr/select3#9]
I think it would be very useful to provide an interface similar like `ajax` but user can decide what's the source of the data.

Option something like this:
```
items: function (term, offset, callback) {
  MyModel.getItems({
   term: term
  }, function (err, results) {
   // transform results
   callback(err, results);
  });
}
```

**Comment by hekike** [comment]
**update:** I see it's possible with `query: function() ...` but the highlighting is not working in this case. Any solution to have it with highlighting?

**Comment by arendjr** [comment]
Can you provide a little code to illustrate the problem? I'm not having highlighting problems with using `query` myself (in fact, the AJAX module uses the same query function under the hood), but maybe there's something in your usage that triggers some bug...

**Comment by hekike** [comment]
@arendjr sry it was my fault. I could fix with `query`. I close the issue.
